name: Deploy Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --debug

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --debug

      - name: Typecheck
        run: tsc --noEmit

      - name: Lint
        run: eslint . --quiet

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  migrate:
    name: 🧬 Apply Migrations
    runs-on: ubuntu-latest
    environment: production
    needs: deploy
    if: success()
    steps:
      - uses: actions/checkout@v4

      - name: Apply pending migrations to the database
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}

  trigger:
    name: 🔫 Deploy Trigger
    runs-on: ubuntu-latest
    needs: [deploy, migrate]
    if: success()
    steps:
      - name: Trigger Deploy
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
        run: |
          npx trigger.dev@latest deploy
